<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
</head>

<body>
  <div class="col-auto" style="text-align:center; margin-top:250px">
    <i style="font-size:40px" class="fa">&#xf1bc;</i>
    <a href="/api/spotify/" class="btn btn-lg btn-success" type="submit" name="search" value="search">Connect with Spotify</a>
  </div>
</body>

</html>